version: 2.1

orbs:
   win: circleci/windows@1.0.0

workflows:
  test:
    jobs:
      - test-linux:
          name: Python 2.7
          docker-image: circleci/python:2.7-jessie
          test-with-codeclimate: true  # we only need to run CodeClimate in one job
      - test-linux:
          name: Python 3.5
          docker-image: circleci/python:3.5-jessie
      - test-linux:
          name: Python 3.6
          docker-image: circleci/python:3.6-jessie
      - test-linux:
          name: Python 3.7
          docker-image: circleci/python:3.7-stretch
      - test-linux:
          name: Python 3.8
          docker-image: circleci/python:3.8-buster
      - test-windows:
          name: Windows Py2.7
          py3: false
      - test-windows:
          name: Windows Py3.3
          py3: true

jobs:
  test-linux:
    parameters:
      docker-image:
        type: string
      consul-supported:
        type: boolean
        default: true
      filesource-supported:
        type: boolean
        default: true
      test-packaging:
        type: boolean
        default: true
      test-with-codeclimate:
        type: boolean
        default: false
    docker:
      - image: <<parameters.docker-image>>
      - image: redis
      - image: amazon/dynamodb-local
      - image: consul
    steps:
      - checkout
      - run:
          name: install requirements
          command: |
            sudo pip install --upgrade pip virtualenv;
            sudo pip install -r test-requirements.txt;
            if [[ "<<parameters.filesource-supported>>" == "true" ]]; then
              sudo pip install -r test-filesource-optional-requirements.txt;
            fi;
            if [[ "<<parameters.consul-supported>>" == "true" ]]; then
              sudo pip install -r consul-requirements.txt;
            fi;
            sudo python setup.py install;
            pip freeze
      - when:
          condition: <<parameters.test-with-codeclimate>>
          steps:
            - run:
                name: run tests (with CodeClimate)
                command: |
                  mkdir test-reports
                  pytest -s --cov=ldclient --junitxml=test-reports/junit.xml testing -W error::SyntaxWarning
                  sh -c '[ -n "${CODECLIMATE_REPO_TOKEN+1}" ] && codeclimate-test-reporter || echo "No CODECLIMATE_REPO_TOKEN value is set; not publishing coverage report"'
      - unless:
          condition: <<parameters.test-with-codeclimate>>
          steps:
            - run:
                name: run tests
                command: |
                  mkdir test-reports
                  pytest -s --junitxml=test-reports/junit.xml testing -W error::SyntaxWarning
      - when:
          condition: <<parameters.test-packaging>>
          steps:
            - run:
                name: test packaging/install
                command: |
                  sudo rm -rf dist *.egg-info
                  ./test-packaging/test-packaging.sh
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

  test-windows:
    executor:
      name: win/vs2019
      shell: powershell.exe
    parameters:
      py3:
        type: boolean
    steps:
      - checkout
      - when:
          condition: <<parameters.py3>>
          steps:
            - run:
                name: install Python 3
                command: choco install python --no-progress
      - unless:
          condition: <<parameters.py3>>
          steps:
            - run:
                name: install Python 2.7
                command: |
                  $ProgressPreference = "SilentlyContinue"  # prevents console errors from CircleCI host
                  iwr -outf python-2.7.16.amd64.msi https://www.python.org/ftp/python/2.7.16/python-2.7.16.amd64.msi
                  Start-Process msiexec.exe -Wait -ArgumentList '/I python-2.7.16.amd64.msi /quiet'
      - run:
          name: set up DynamoDB
          command: |
            $ProgressPreference = "SilentlyContinue"
            iwr -outf dynamo.zip https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.zip
            mkdir dynamo
            Expand-Archive -Path dynamo.zip -DestinationPath dynamo
            cd dynamo
            javaw -D"java.library.path=./DynamoDBLocal_lib" -jar DynamoDBLocal.jar
          background: true
      - run:
          name: set up Consul
          command: |
            $ProgressPreference = "SilentlyContinue"
            iwr -outf consul.zip https://releases.hashicorp.com/consul/1.4.2/consul_1.4.2_windows_amd64.zip
            mkdir consul
            Expand-Archive -Path consul.zip -DestinationPath consul
            cd consul
            sc.exe create "Consul" binPath="$(Get-Location)/consul.exe agent -dev"
            sc.exe start "Consul"
      - run:
          name: start Redis
          command: |
            $ProgressPreference = "SilentlyContinue"
            iwr -outf redis.zip https://github.com/MicrosoftArchive/redis/releases/download/win-3.0.504/Redis-x64-3.0.504.zip
            mkdir redis
            Expand-Archive -Path redis.zip -DestinationPath redis
            cd redis
            ./redis-server --service-install
            ./redis-server --service-start
            Start-Sleep -s 5
            ./redis-cli ping
      - run:
          name: install requirements
          command: |
            $env:Path += ";C:\Python27\;C:\Python27\Scripts\"  # has no effect if 2.7 isn't installed
            python --version
            pip install -r test-requirements.txt
            pip install -r consul-requirements.txt
            python setup.py install
      - run:
          name: run tests
          command: |
            mkdir test-reports
            $env:Path += ";C:\Python27\;C:\Python27\Scripts\"  # has no effect if 2.7 isn't installed
            python -m pytest -s --junitxml=test-reports/junit.xml testing;
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
